---
title: "Childhood Trauma Questionnaire"
output: html_document
date: '2022-05-15'
author: 'Taiming Xue'
---
## Background

This scale was developed by David Bernstein and colleagues and includes a 28-item self-report measure (Berstein, et al., 1998). The CTQ is designed to examine traumatic childhood experiences in adults and adolescents. Questions focus on traumatic experiences and measure 5 types of maltreatment – emotional, physical, and sexual abuse, and emotional and physical neglect.. Items are scored on a Likert scale from 1 (never true) to 5 (very often true). High scores indicate more trauma (Wright et al., 2001). 

CTQ has previously been examined and used in many different papers. Some examples are listed below:
[Development and validation of a brief screening version of the Childhood Trauma Questionnaire](https://www.sciencedirect.com/science/article/pii/S0145213402005410#:~:text=To%20address%20the%20need%20for,et%20al.%2C%201994)

[Factorial validity of the Childhood Trauma Questionnaire in men and women](https://pubmed.ncbi.nlm.nih.gov/11413564/)

## Scoresheet
To clean the data, the scoresheet:

(1) selects only variables that are relevant for the current measure

(2) recodes variables that need to be reversely coded (e.g. 'Never true =1' to 'never true = 5')

(3) creates five additional variables based on sum scores reflecting five subscales of the questionnaire: emotional abuse, physical abuse, sexual abuse, emotional neglect, physical neglect.

(4) creates an additional variable based on sum scores of three questions to help determine if respondents are underreporting their childhood trauma.

(5) selects only a few columns that will go into the final dataset

(6) creates five additional variables to include records that answered more than 25% of questions in each subscale in the questionnaires 

(7) creates five additional variable based on sum score. The new variable splits cases into non to minimal, low to moderate, moderate to severe, and severe to extreme childhood maltreatment.


## Key Variables
`ctq_emotional_abuse`(reflects participant's emotional abuse history)
`ctq_physical_abuse`(reflects participant's physical abuse history)
`ctq_sexual_abuse`(reflects participant's sexual abuse history)
`ctq_emotional_neglect`(reflects participant's emotional neglect history)
`ctq_physical_neglect`(reflects participant's physical neglect history)
`ctq_minimization_denial`(detects the underreporting of maltreatment)

```{r}
library(haven)
library(cgwtools)
library(scorekeeper)
library(readxl)


load('BAM_RA_raw.Rdata')
CTQ_scoresheet <- read_excel("CTQ_scoresheet.xlsx")
cleaned_data <- scorekeep(BAM_RA_raw, CTQ_scoresheet)
cleaned_ctq_data <- cleaned_data[[6]]
save(cleaned_ctq_data, file = 'cleaned_ctq.RData')
```

