---
title: "Eating Disorder Diagnostic Scale Companion"
output: html_document
---


## 1. Background

This companion file is for the Eating Disorder Diagnostic scale, which is a 22-item self-report questionnaire designed to measure Anorexia nervosa, Bulimia nervosa, and Binge-eating disorder symptomatology aligned with the DSM-IV diagnostic criteria. The scale is comprised of a combination of Likert ratings, dichotomous scores, behavioural frequency scores, and open-ended questions asking for weight and height.

Reference 1: ["Development and validation of the Eating Disorder Diagnostic Scale: A brief self-report measure of anorexia, bulimia, and binge-eating disorder"] (https://psycnet.apa.org/record/2000-02501-017)

Reference 2: [Eating Disorder Diagnostic Scale: Additional Evidence of Reliability and Validity.] (https://psycnet.apa.org/record/2004-11653-007)

## 2. Scoresheet

In order to clean the data:

(1) Selects raw variables being used for the current measure

(2) Renames variables to be easily identified

(3) Sum the total scores and rename this summary as edhistory_sum


## 3. Key Variables

`edhistory_weightloss`
`edhistory_fear_fat`
`edhistory_feel_fat`
`edhistory_thin`
`edhistory_danger`
`edhistory_limit_food`
`edhistory_concentrate`
`edhistory_binge`
`edhistory_not_hungry`
`edhistory_alone`
`edhistory_guilt`
`edhistory_upset`
`edhistory_self_vomit`
`edhistory_laxatives`
`edhistory_diuretics`
`edhistory_fast`
`edhistory_exercise`

```{r}
library(readxl)
library(haven)
library(cgwtools)
library(scorekeeper)

load("C:\\Users\\andik\\Downloads\\BAM_RA_raw.Rdata")

edhistory_scoresheet <- read_excel("C:/Users/andik/OneDrive/Documents/R/ed_history_scoresheet.xlsx")

edhistory_cleaned <- scorekeep(BAM_RA_raw, edhistory_scoresheet)
```
