---
title: "EPSI"
author: "Taiming Xue"
date: '2022-09-21'
output: html_document
---


## Background

Eating Pathology Symptoms Inventory (EPSI) is a self-report questionnaire that includes 45 items covering 8 subscales: Body Dissatisfaction, Binge Eating, Cognitive Restraint, Purging, Restricting, Excessive Exercise, Negative Attitudes toward Obesity, and Muscle Building. Each item is scored on a 5-point Likert-style scale (0 = Never; 4= Often) to describe how well each item describes the participant experiences. Scores are derived by summing responses across the questions included in each subscale.

EPSI has previously been examined and used in many different papers. Some examples are listed below:

[Development and validation of the Eating Pathology Symptoms Inventory (EPSI) by Wilds et al](https://doi.org/10.1037/a0032639)

[Factorial integrity and validation of the Eating Pathology Symptoms Inventory (EPSI)](https://doi.org/10.1016/j.eatbeh.2018.07.004)

## Scoresheet

To clean the data, the scoresheet:

1) selects only the variables that are relevant for the current measure

2) rename raw variables to appropraite names that are easy to understand

3) creates eight additional variables based on sum scores reflecting eight subscales of the questionnaire: Body Dissatisfaction, Binge Eating, Cognitive Restraint, Purging, Restricting, Excessive Exercise, Negative Attitudes toward Obesity, and Muscle Building

4) select only a few columns that will go into the final dataset

## Key variables
The variables below are sum of different subscales

`epsi_body_dissatisfaction` (reflects participant's body dissatisfaction symptoms)

`epsi_binge_eating` (reflects participant's binge eating symptoms)

`epsi_cognitive_restraint` (reflects participant's cognitive restraint symptoms)

`epsi_purging` (reflects participant's purging symptoms)

`epsi_restricting` (reflects participant's restricting symptoms)

`epsi_excessive_exercise` (reflects participant's excessive exercise symptoms)

`epsi_negative_attitude` (reflects participant's negative attidtude towards obesity symptoms)

`epsi_muscle_building` (reflects participant's muscle building symptoms)

```{r, echo=FALSE}
library(haven)
library(cgwtools)
library(readxl)
library(scorekeeper)




MAXED_raw <- read.csv('MAXED_RA_raw.csv')

EPSI_scoresheet <- read_excel('EPSI_Clean.xlsx')

cleaned_data <- scorekeep(MAXED_raw, EPSI_scoresheet)

EPSI_Cleaned <- cleaned_data[[4]]

save(EPSI_Cleaned, file = 'epsi_cleaned.RData')
```

