
---
title: "GAD"
author: "Taiming Xue"
date: '2022-05-07'
output: html_document
---



## Background

Generalized Anxiety Disorder 7-item (GAD-7) is a seven-item instrument that is used to measure or assess the severity of generalised anxiety disorder (GAD). Each item asks the individual to rate the severity of his or her symptoms over the past two weeks. Response options include “not at all”, “several days”, “more than half the days” and “nearly every day”.

GAD-7 has previously been examined and used in many different papers. Some examples are listed below:

[Using Generalized Anxiety Disorder-2 (GAD-2) and GAD-7 in a Primary Care Setting](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7306644/)

[A Brief Measure for Assessing Generalized Anxiety Disorder: The GAD-7](https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/410326)

## Scoresheet

To clean the data, the scoresheet:

1) selects only the variables that are relevant for the current measure

2) recode raw variables to make them consistent with the way of scoring: not at all =0, several days =1, over half the days =2, nearly every day =3

3) creates an additional variable based on sum scores reflecting the participant's anxiety levels

4) select only a few columns that will go into the final dataset

## Key variables
The variable below is sum of all variables

`gad_sum` 

```{r, echo=FALSE}
library(haven)
library(readxl)
library(dplyr)
library(scorekeeper)



load('BAM_RA_raw.Rdata')

GAD7_scoresheet <- read_excel('GAD7_Clean.xlsx')

cleaned_data <- scorekeep(BAM_RA_raw, GAD7_scoresheet)

GAD7_Cleaned <- cleaned_data[[5]]

save(GAD7_Cleaned, file = 'gad7_cleaned.RData'
=======