---
title: "companion_gffs"
author: "Danielle Lennon"
date: '2022-04-25'
output: html_document
---

## 1. Background

This companion file is for the Goldfarb Fear of Fat Scale (GFFS) which was introduced in 1985 as a diagnostic tool to measure one's fear of fat as it can be an indicator for the development of an eating disorder (Goldfarb et al., 1985). When used as a screening tool for both clinical and non-clinical groups, GFFS has strong test-retest reliability and psychometric properties (Pryzbyla-Basista et al., 2022). In addition, the test also has shown high validity for both populations with and without eating disorders (Goldfarb, 2010). GFFS uses a 4-point scale with 1 being equal to very untrue and 4 being equal to very true. 


[The Goldfarb Fear of Fat Scale](https://pubmed.ncbi.nlm.nih.gov/3861845/)
[An examination of the factor structure of the Goldfarb Fear of Fat Scale in clinical and non-clinical samples of Polish women](https://www.sciencedirect.com/science/article/pii/S1740144521001467)
[Measures for Clinical Practice and Research: A Sourcebook, 4th edition](https://www.magiworld.org/Journal/2010/1008_Measures.pdf)
##
## 2. Scoresheet

In order to clean the data:

- Select raw variables being used

- Rename variables to include numbering for order of questions in the scale

- Recode labels scale to begin at 0 instead of 1 with very untrue being equal to 0 and very true being equal to 3

- Sum the total scores and rename this summary as `gffs_sum`

##
## 3. Key Variables
 
`gffs_1_fear_fat` (assesses if biggest fear is becoming fat)
`gffs_2_fear_little_gain` (assesses fear of minor weight gain)
`gffs_3_overweight_risk` (assesses fear of becoming overweight)
`gffs_4_cannot_live` (assesses opinions of how overweight people can live)
`gffs_5_fat_worst` (assesses if becoming fat is worst outcome)
`gffs_6_concentrate` (assesses if concentration on weight control prevents becoming fat)
`gffs_7_painful_thought` (assesses if thoughts of weight gain being fearful can be controlled)
`gffs_8_energy_control_weight` (assesses energy that goes towards weight control)
`gffs_9_eat_lose_control` (assesses fear of losing control when eating)
`gffs_10_stay_hungry` (assesses if staying hungry is meant to prevent becoming fat)
`gffs_sum` (sum of answers for the previous 10 variables)
##
```{r, echo=FALSE}
library(readxl)
gffs_clean <- read_excel("~/gffs_clean.xlsx")
library(cgwtools)
library(scorekeeper)

cleaned_data <- scorekeep(BAM_RA_raw, gffs_clean)

cleaned_gffs_data <- cleaned_data[[4]]

```

