---
title: "tmfs companion"
author: "Danielle Lennon"
date: '2022-05-12'
output: html_document
---

## 1. Background

This companion file is for the Traditional Masculinity-Femininity Scale (TMFS) which was introduced in 2016 to assess self-ascribed masculinity and femininity (Kachel et al., 2016). TMFS has demonstrated high reliability for both sexes (Kachel et al., 2016). Additionally, TMFS shows validity due to its ability to reduce issues of social desirability when given as a self-assessment (Kachel et al., 2016). TMFS uses a 7-point likert scale with 1 being equal to totally masculine and 7 being equal to totally feminine. In terms of scoring, the mean is taken of all given answers with an average less than 4 implying masculinity and an average greater than 4 implying femininity.


[Traditional Masculinity and Femininity: Validation of a New Scale Assessing Gender Roles ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4932111/)

##
## 2. Scoresheet

In order to clean the data:

- Select raw variables being used

- Rename variables to include numbering of questions in the scale

- Average the total scores and rename as `tmfs_mean`
##
## 3. Key Variables

`tmfs_mean` (average of scores in response to questions asking about different situations where one could consider their femininity and masculinity)

##
```{r, echo=FALSE}
library(readxl)
tmfs_clean <- read_excel("~/tmfs_clean.xlsx")
library (cgwtools)
library(scorekeeper)

cleaned_data <- scorekeep(BAM_RA_raw, tmfs_clean)

cleaned_tmfs_data <- cleaned_data[[4]]

```
