---
title: "umb-fat companion"
author: "Danielle Lennon"
date: '2022-05-12'
output: html_document
---
## 1. Background

This companion file is for the Universal Measure of Bias - Fat (UMB-Fat) which was introduced in 2008 to assess weight bias and demonstrates strong psychometric properties when utilized as an assessment (Durso et al., 2008). It has been compared alongside two other scales measuring universal bias against 'gay' or 'Muslim' individuals and demonstrates high internal consistency and construct validity (Latner et al., 2008). UMB-Fat uses a 7-point likert scale with 1 being equal to strongly agree and 7 being equal to strongly disagree. In terms of scoring, sums of scores are separated amongst four categories of bias: adverse judgement, social distance, attraction, and equal rights. 


[Understanding self-directed stigma: development of the weight bias internalization scale ](https://pubmed.ncbi.nlm.nih.gov/18978768/)
[Weighing obesity stigma: the relative strength of different forms of bias ](https://pubmed.ncbi.nlm.nih.gov/18414421/)
[UMB-FAT](https://www.researchgate.net/publication/262414384_UMB-FAT)
##
## 2. Scoresheet

In order to clean the data:

- Select raw variables being used

- Rename variables to include descriptors of questions asked in the scale 

- Reverse code questions 5, 7, 8, 9, 12, 15, 16, and 19 so that higher scores indicate greater stigma

- Sum the total scores of questions 5, 7, 12 ,15 , 16  and rename as `umb_adverse_judgement_sum`

- Sum the total scores of questions 2, 8, 17, 19, 20  and rename as `umb_social_distance_sum`

- Sum the total scores of questions 3, 4, 6, 9, 10 and rename as `umb_attraction_sum`

- Sum the total scores of questions 1, 11, 13, 14, 18 and rename as `umb_equal_rights_sum`

##
## 3. Key Variables
 
`umb_adverse_judgement_sum` (sum of scores for questions identifying bias in the form of adverse judgement against fat people)
`umb_social_distance_sum` (sum of scores for questions identifying bias in the form of social distance from fat people)
`umb_attraction_sum` (sum of scores for questions identifying bias in the form of attraction towards fat people)
`umb_equal_rights_sum` (sum of scores for questions identifying bias in the form of opions of equal rights for fat people)

##
```{r, echo=FALSE}
library(readxl)
umb_fat_clean <- read_excel("~/umb_fat_clean.xlsx")
library (cgwtools)
library(scorekeeper)

cleaned_data <- scorekeep(BAM_RA_raw, umb_fat_clean)

cleaned_umb_fat_data <- cleaned_data[[4]]

```
